# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=550)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('votes_count', models.IntegerField(default=0)),
                ('answers_count', models.PositiveIntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_questions', to='answers.answer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
