# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_tags', '0001_initial'),
        ('questions', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='tags.tag'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(fields=('question', 'tag'), name='unique_question_tag'),
        ),
    ]
