# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('quiz', models.JSONField(blank=True, default=list)),
                ('challenge', models.JSONField(blank=True, null=True)),
                ('completion_rule', models.CharField(choices=[('manual', 'Manual'), ('read', 'Read'), ('quiz', 'Quiz'), ('challenge', 'Challenge')], default='manual', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_modules.coursemodule')),
            ],
            options={
                'ordering': ['order_index'],
                'constraints': [models.UniqueConstraint(fields=('module', 'order_index'), name='unique_module_lesson_order')],
            },
        ),
    ]
