# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_modules', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order_index'), name='unique_course_module_order'),
        ),
    ]
