# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_snippets', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_tags', to='code_snippets.codesnippet')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_tags', to='tags.tag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snippet', 'tag'), name='unique_snippet_tag')],
            },
        ),
    ]
