# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChallengeCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_id', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('code_submitted', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to='lessons.lesson')),
            ],
        ),
    ]
