# Generated by Django 6.0.7 on 2026-07-10 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_certificates', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='coursecertificate',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_course_certificate'),
        ),
    ]
